//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaptainMao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class shoppingcart
    {
        public int cartID { get; set; }
        public string userID { get; set; }
        public int Merchandise_ID { get; set; }
        public int merchandise_Volume { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual Merchandise Merchandise { get; set; }
    }
}
